import { buildPesel } from "@/lib/pesel";
import type { DoctorPatient } from "@/lib/doctor/types";

const now = new Date().toISOString();

function p(
  partial: Omit<DoctorPatient, "createdAt" | "updatedAt"> & {
    createdAt?: string;
    updatedAt?: string;
  }
): DoctorPatient {
  return {
    ...partial,
    createdAt: partial.createdAt ?? now,
    updatedAt: partial.updatedAt ?? now,
  };
}

/**
 * 18 realistycznych pacjentów PL, ID stabilne (p-001…),
 * PESEL z poprawną sumą kontrolną (buildPesel).
 * Zsynchronizowane z seed-visits (patientId).
 */
export const SEED_PATIENTS: DoctorPatient[] = [
  p({
    id: "p-001",
    firstName: "Anna",
    lastName: "Kowalska",
    pesel: buildPesel(1985, 3, 12, 123, "K"),
    birthDate: "1985-03-12",
    sex: "K",
    phone: "500111001",
    email: "anna.kowalska@email.pl",
    street: "Lipowa",
    buildingNo: "12",
    apartmentNo: "4",
    postalCode: "15-424",
    city: "Białystok",
    cardNumber: "CMKW-0001",
    groups: ["Prywatny", "VIP"],
    notes: "Alergia na penicylinę (zgłoszone).",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-002",
    firstName: "Piotr",
    lastName: "Wiśniewski",
    pesel: buildPesel(1978, 9, 5, 45, "M"),
    birthDate: "1978-09-05",
    sex: "M",
    phone: "501222003",
    email: "piotr.wisniewski@email.pl",
    street: "Sienkiewicza",
    buildingNo: "8",
    apartmentNo: "",
    postalCode: "15-092",
    city: "Białystok",
    cardNumber: "CMKW-0002",
    groups: ["NFZ"],
    notes: "Po artroskopii kolana L (2025).",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-003",
    firstName: "Magdalena",
    lastName: "Zielińska",
    pesel: buildPesel(1992, 4, 18, 210, "K"),
    birthDate: "1992-04-18",
    sex: "K",
    phone: "502333004",
    email: "m.zielinska@email.pl",
    street: "Wyszyńskiego",
    buildingNo: "3",
    apartmentNo: "12",
    postalCode: "15-888",
    city: "Białystok",
    cardNumber: "CMKW-0003",
    groups: ["Sport", "Prywatny"],
    notes: "Siatkówka – klub lokalny.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-004",
    firstName: "Krzysztof",
    lastName: "Jankowski",
    pesel: buildPesel(1965, 7, 22, 88, "M"),
    birthDate: "1965-07-22",
    sex: "M",
    phone: "503444005",
    email: "k.jankowski@email.pl",
    street: "Piastowska",
    buildingNo: "45",
    apartmentNo: "1",
    postalCode: "15-207",
    city: "Białystok",
    cardNumber: "CMKW-0004",
    groups: ["Pooperacyjny", "Prywatny"],
    notes: "Endoproteza biodra P – 6 tyg. temu.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-005",
    firstName: "Ewa",
    lastName: "Lewandowska",
    pesel: buildPesel(1988, 1, 1, 301, "K"),
    birthDate: "1988-01-01",
    sex: "K",
    phone: "504555006",
    email: "ewa.lew@email.pl",
    street: "Jurowiecka",
    buildingNo: "1",
    apartmentNo: "7",
    postalCode: "15-101",
    city: "Białystok",
    cardNumber: "CMKW-0005",
    groups: ["Nowy", "Prywatny"],
    notes: "Pierwsza wizyta w CMKW.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-006",
    firstName: "Marek",
    lastName: "Szymański",
    pesel: buildPesel(1972, 6, 30, 55, "M"),
    birthDate: "1972-06-30",
    sex: "M",
    phone: "505666007",
    email: "marek.s@email.pl",
    street: "Antoniukowska",
    buildingNo: "22",
    apartmentNo: "",
    postalCode: "15-740",
    city: "Białystok",
    cardNumber: "CMKW-0006",
    groups: ["NFZ"],
    notes: "Rehabilitacja stawu skokowego.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-007",
    firstName: "Joanna",
    lastName: "Dąbrowska",
    pesel: buildPesel(1995, 2, 14, 77, "K"),
    birthDate: "1995-02-14",
    sex: "K",
    phone: "506777008",
    email: "j.dabrowska@email.pl",
    street: "Młynowa",
    buildingNo: "9",
    apartmentNo: "2",
    postalCode: "15-404",
    city: "Białystok",
    cardNumber: "CMKW-0007",
    groups: ["Prywatny"],
    notes: "Częste odwołania – preferuje popołudnia.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-008",
    firstName: "Tomasz",
    lastName: "Wójcik",
    pesel: buildPesel(1981, 4, 11, 19, "M"),
    birthDate: "1981-04-11",
    sex: "M",
    phone: "507888009",
    email: "t.wojcik@email.pl",
    street: "Świętojańska",
    buildingNo: "15",
    apartmentNo: "6",
    postalCode: "15-082",
    city: "Białystok",
    cardNumber: "CMKW-0008",
    groups: ["VIP", "Sport"],
    notes: "Podejrzenie uszkodzenia ACL.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-009",
    firstName: "Agnieszka",
    lastName: "Kamińska",
    pesel: buildPesel(1990, 8, 25, 142, "K"),
    birthDate: "1990-08-25",
    sex: "K",
    phone: "508999010",
    email: "a.kaminska@email.pl",
    street: "Pogodna",
    buildingNo: "4",
    apartmentNo: "",
    postalCode: "15-354",
    city: "Białystok",
    cardNumber: "CMKW-0009",
    groups: ["Prywatny"],
    notes: "Kwalifikacja do PRP.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-010",
    firstName: "Robert",
    lastName: "Kaczmarek",
    pesel: buildPesel(1970, 5, 3, 33, "M"),
    birthDate: "1970-05-03",
    sex: "M",
    phone: "509000011",
    email: "r.kaczmarek@email.pl",
    street: "Hetmańska",
    buildingNo: "30",
    apartmentNo: "11",
    postalCode: "15-727",
    city: "Białystok",
    cardNumber: "CMKW-0010",
    groups: ["NFZ", "Pooperacyjny"],
    notes: "RHB pooperacyjna barku.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-011",
    firstName: "Beata",
    lastName: "Piotrowska",
    pesel: buildPesel(1986, 9, 17, 90, "K"),
    birthDate: "1986-09-17",
    sex: "K",
    phone: "510111012",
    email: "beata.p@email.pl",
    street: "Wiejska",
    buildingNo: "7",
    apartmentNo: "3",
    postalCode: "15-351",
    city: "Białystok",
    cardNumber: "CMKW-0011",
    groups: ["Prywatny"],
    notes: "Hallux valgus – konsultacja.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-012",
    firstName: "Paweł",
    lastName: "Grabowski",
    pesel: buildPesel(1993, 1, 28, 64, "M"),
    birthDate: "1993-01-28",
    sex: "M",
    phone: "511222013",
    email: "p.grabowski@email.pl",
    street: "Zwierzyniecka",
    buildingNo: "18",
    apartmentNo: "",
    postalCode: "15-333",
    city: "Białystok",
    cardNumber: "CMKW-0012",
    groups: ["Sport", "Nowy"],
    notes: "Biegacz amator.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-013",
    firstName: "Halina",
    lastName: "Michalska",
    pesel: buildPesel(1955, 6, 12, 11, "K"),
    birthDate: "1955-06-12",
    sex: "K",
    phone: "512333014",
    email: "h.michalska@email.pl",
    street: "Ciepła",
    buildingNo: "2",
    apartmentNo: "5",
    postalCode: "15-471",
    city: "Białystok",
    cardNumber: "CMKW-0013",
    groups: ["NFZ", "VIP"],
    notes: "Kontrola po złamaniu nadgarstka.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-014",
    firstName: "Marcin",
    lastName: "Adamczyk",
    pesel: buildPesel(1988, 7, 30, 202, "M"),
    birthDate: "1988-07-30",
    sex: "M",
    phone: "513444015",
    email: "m.adamczyk@email.pl",
    street: "Poleska",
    buildingNo: "50",
    apartmentNo: "8",
    postalCode: "15-855",
    city: "Białystok",
    cardNumber: "CMKW-0014",
    groups: ["Prywatny"],
    notes: "",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-015",
    firstName: "Natalia",
    lastName: "Sikora",
    pesel: buildPesel(1998, 2, 3, 150, "K"),
    birthDate: "1998-02-03",
    sex: "K",
    phone: "514555016",
    email: "n.sikora@email.pl",
    street: "Skorupska",
    buildingNo: "11",
    apartmentNo: "",
    postalCode: "15-879",
    city: "Białystok",
    cardNumber: "CMKW-0015",
    groups: ["Prywatny", "Sport"],
    notes: "Bieganie – kontuzja kolana.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-016",
    firstName: "Grzegorz",
    lastName: "Baran",
    pesel: buildPesel(1975, 4, 19, 27, "M"),
    birthDate: "1975-04-19",
    sex: "M",
    phone: "515666017",
    email: "g.baran@email.pl",
    street: "Świętego Rocha",
    buildingNo: "6",
    apartmentNo: "2",
    postalCode: "15-879",
    city: "Białystok",
    cardNumber: "CMKW-0016",
    groups: ["Prywatny"],
    notes: "Skierowanie na USG w toku.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-017",
    firstName: "Iwona",
    lastName: "Czarnecka",
    pesel: buildPesel(1991, 5, 8, 88, "K"),
    birthDate: "1991-05-08",
    sex: "K",
    phone: "516777018",
    email: "i.czarnecka@email.pl",
    street: "Brukowa",
    buildingNo: "14",
    apartmentNo: "9",
    postalCode: "15-889",
    city: "Białystok",
    cardNumber: "CMKW-0017",
    groups: ["NFZ"],
    notes: "Plan RHB 10 sesji – blisko końca.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-018",
    firstName: "Dariusz",
    lastName: "Ostrowski",
    pesel: buildPesel(1968, 9, 15, 41, "M"),
    birthDate: "1968-09-15",
    sex: "M",
    phone: "517888019",
    email: "d.ostrowski@email.pl",
    street: "Kawaleryjska",
    buildingNo: "25",
    apartmentNo: "",
    postalCode: "15-123",
    city: "Białystok",
    cardNumber: "CMKW-0018",
    groups: ["Pooperacyjny"],
    notes: "Historia nieobecności na wizytach.",
    rodConsent: true,
    rodConsentAt: now,
    status: "inactive",
  }),
  p({
    id: "p-019",
    firstName: "Katarzyna",
    lastName: "Lis",
    pesel: buildPesel(1987, 6, 26, 99, "K"),
    birthDate: "1987-06-26",
    sex: "K",
    phone: "518999020",
    email: "k.lis@email.pl",
    street: "Zwycięstwa",
    buildingNo: "40",
    apartmentNo: "15",
    postalCode: "15-703",
    city: "Białystok",
    cardNumber: "CMKW-0019",
    groups: ["VIP", "Prywatny"],
    notes: "Preferuje wizyty poranne.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
  p({
    id: "p-020",
    firstName: "Łukasz",
    lastName: "Majewski",
    pesel: buildPesel(1994, 1, 12, 73, "M"),
    birthDate: "1994-01-12",
    sex: "M",
    phone: "519000021",
    email: "l.majewski@email.pl",
    street: "Upalna",
    buildingNo: "5",
    apartmentNo: "1",
    postalCode: "15-668",
    city: "Białystok",
    cardNumber: "CMKW-0020",
    groups: ["Nowy", "Sport"],
    notes: "Uraz sportowy – pierwsza wizyta.",
    rodConsent: true,
    rodConsentAt: now,
    status: "active",
  }),
];

export function getSeedPatientById(id: string): DoctorPatient | undefined {
  return SEED_PATIENTS.find((x) => x.id === id);
}
