import type { EPrescription, EReferral } from "@/lib/doctor/ehealth-types";
import { subDays } from "date-fns";

const now = new Date();
const iso = (daysAgo: number, hour = 10) => {
  const d = subDays(now, daysAgo);
  d.setHours(hour, 15, 0, 0);
  return d.toISOString();
};

/**
 * Seed e-recept i e-skierowań powiązanych z wizytami seed (v-001, v-003, …).
 * Numery realistyczne (mock P1) — nie są prawdziwymi dokumentami CeZ.
 */
export const SEED_E_PRESCRIPTIONS: EPrescription[] = [
  {
    id: "epx-001",
    number: "4821-7390-1564",
    accessCode: "8472",
    status: "issued",
    kind: "30_days",
    visitId: "v-001",
    patientId: "p-001",
    patientName: "Anna Kowalska",
    patientPesel: "", // uzupełniane w runtime z pacjenta przy wyświetlaniu
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    doctorPwz: "1234567",
    items: [
      {
        id: "epi-001",
        drugId: "drug-001",
        drugName: "Ketonal Forte",
        inn: "Ketoprofenum",
        form: "tabletki powlekane",
        strength: "100 mg",
        dosage: "1 tabl. 1×/d z posiłkiem",
        quantity: "1 op. (20 tabl.)",
        duration: "20 dni",
        frequency: "1× dziennie rano",
        notes: "Przy dolegliwościach żołądkowych + IPP",
      },
      {
        id: "epi-002",
        drugId: "drug-029",
        drugName: "Omeprazol Sandoz",
        inn: "Omeprazolum",
        form: "kapsułki",
        strength: "20 mg",
        dosage: "1 kaps. rano na czczo",
        quantity: "1 op. (28 kaps.)",
        duration: "28 dni",
        frequency: "1× dziennie",
        notes: "",
      },
    ],
    generalNotes: "NLPZ + osłona żołądka. Kontrola po MRI.",
    issuedAt: iso(0, 8),
    p1Ready: true,
    createdAt: iso(0, 8),
    updatedAt: iso(0, 8),
  },
  {
    id: "epx-002",
    number: "5910-2847-6631",
    accessCode: "3019",
    status: "issued",
    kind: "annual",
    visitId: "v-003",
    patientId: "p-003",
    patientName: "Magdalena Zielińska",
    patientPesel: "",
    doctorId: "frankowski",
    doctorName: "Lek. Paweł Frankowski",
    doctorPwz: "3456789",
    items: [
      {
        id: "epi-003",
        drugId: "drug-038",
        drugName: "Voltaren Emulgel",
        inn: "Diclofenacum diethylaminum",
        form: "żel",
        strength: "1%",
        dosage: "cienka warstwa 3×/d na bark",
        quantity: "2 op. (100 g)",
        duration: "do 3 mies. (recepta roczna — realizacja częściowa)",
        frequency: "3× dziennie",
        notes: "Miejscowo, nie stosować na uszkodzoną skórę",
      },
    ],
    generalNotes: "Recepta roczna — kontynuacja leczenia miejscowego po urazie barku.",
    issuedAt: iso(2, 9),
    p1Ready: true,
    createdAt: iso(2, 9),
    updatedAt: iso(2, 9),
  },
  {
    id: "epx-003",
    number: "1102-8841-5570",
    accessCode: "6620",
    status: "cancelled",
    kind: "30_days",
    visitId: "v-001",
    patientId: "p-001",
    patientName: "Anna Kowalska",
    patientPesel: "",
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    doctorPwz: "1234567",
    items: [
      {
        id: "epi-004",
        drugId: "drug-002",
        drugName: "Aulin",
        inn: "Nimesulidum",
        form: "saszetki",
        strength: "100 mg",
        dosage: "1 sasz. 2×/d po posiłku",
        quantity: "1 op. (30 sasz.)",
        duration: "max 15 dni",
        frequency: "2× dziennie",
        notes: "Anulowano — zmiana na Ketonal",
      },
    ],
    generalNotes: "Anulowana — zastąpiona epx-001.",
    issuedAt: iso(1, 14),
    cancelledAt: iso(0, 8),
    cancelReason: "Zmiana leku na Ketonal Forte + IPP",
    p1Ready: false,
    createdAt: iso(1, 14),
    updatedAt: iso(0, 8),
  },
];

export const SEED_E_REFERRALS: EReferral[] = [
  {
    id: "eref-001",
    number: "ES-2026-004821",
    accessCode: "5512",
    status: "issued",
    visitId: "v-001",
    patientId: "p-001",
    patientName: "Anna Kowalska",
    patientPesel: "",
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    doctorPwz: "1234567",
    examCategory: "Obrazowanie",
    examType: "MRI kolana",
    justification:
      "Ból kolana prawego od 3 mies., podejrzenie uszkodzenia łąkotki / gonartroza. Konieczna ocena MRI przed dalszym leczeniem.",
    urgency: "normal",
    targetFacility: "Pracownia MRI — partner zewnętrzny",
    icdCode: "M17.1",
    issuedAt: iso(0, 8),
    p1Ready: true,
    createdAt: iso(0, 8),
    updatedAt: iso(0, 8),
  },
  {
    id: "eref-002",
    number: "ES-2026-003910",
    accessCode: "7741",
    status: "issued",
    visitId: "v-003",
    patientId: "p-003",
    patientName: "Magdalena Zielińska",
    patientPesel: "",
    doctorId: "frankowski",
    doctorName: "Lek. Paweł Frankowski",
    doctorPwz: "3456789",
    examCategory: "Obrazowanie",
    examType: "USG stawu barkowego",
    justification:
      "Uraz barku L (siatkówka). Ból nocny, ograniczenie uniesienia. Podejrzenie impingement / uszkodzenie stożka rotatorów.",
    urgency: "urgent",
    targetFacility: "CMKW Białystok — Szymborskiej 2/U4",
    icdCode: "M75.1",
    issuedAt: iso(2, 9),
    p1Ready: true,
    createdAt: iso(2, 9),
    updatedAt: iso(2, 9),
  },
  {
    id: "eref-003",
    number: "ES-2026-002155",
    accessCode: "1903",
    status: "cancelled",
    visitId: "v-002",
    patientId: "p-002",
    patientName: "Piotr Wiśniewski",
    patientPesel: "",
    doctorId: "wenta",
    doctorName: "Lek. Tomas Wenta",
    doctorPwz: "2345678",
    examCategory: "Rehabilitacja",
    examType: "Fizjoterapia pooperacyjna",
    justification: "Kontrola po artroskopii — skierowanie anulowane, rehabilitacja w innym ośrodku.",
    urgency: "normal",
    targetFacility: "Do wyboru przez pacjenta",
    icdCode: "M23.2",
    issuedAt: iso(14, 11),
    cancelledAt: iso(10, 9),
    cancelReason: "Pacjent kontynuuje rehabilitację prywatnie",
    p1Ready: false,
    createdAt: iso(14, 11),
    updatedAt: iso(10, 9),
  },
];
