import type { DoctorVisit } from "@/lib/doctor/types";
import { format, addDays, subDays } from "date-fns";

/**
 * Deterministyczne seed-y wizyt EDM (15–20).
 * Daty względne do „dziś”, żeby kalendarz zawsze miał treść.
 */
function d(offset: number): string {
  return format(addDays(new Date(), offset), "yyyy-MM-dd");
}

function past(offset: number): string {
  return format(subDays(new Date(), offset), "yyyy-MM-dd");
}

const now = new Date().toISOString();

export const SEED_VISITS: DoctorVisit[] = [
  {
    id: "v-001",
    date: d(0),
    time: "08:00",
    patientFirstName: "Anna",
    patientLastName: "Kowalska",
    patientPesel: "85031212345",
    patientGroups: ["Prywatny", "VIP"],
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    status: "confirmed",
    type: "konsultacja",
    note: "Ból kolana prawego, MRI w toku",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-002",
    date: d(0),
    time: "08:30",
    patientFirstName: "Piotr",
    patientLastName: "Wiśniewski",
    patientPesel: "78090512345",
    patientGroups: ["NFZ"],
    doctorId: "wenta",
    doctorName: "Lek. Tomas Wenta",
    status: "scheduled",
    type: "kontrolna",
    note: "Kontrola po artroskopii",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-003",
    date: d(0),
    time: "09:00",
    patientFirstName: "Magdalena",
    patientLastName: "Zielińska",
    patientPesel: "92041812345",
    patientGroups: ["Sport", "Prywatny"],
    doctorId: "frankowski",
    doctorName: "Lek. Paweł Frankowski",
    status: "confirmed",
    type: "konsultacja",
    note: "Uraz barku – siatkówka",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-004",
    date: d(0),
    time: "09:30",
    patientFirstName: "Krzysztof",
    patientLastName: "Jankowski",
    patientPesel: "65072212345",
    patientGroups: ["Pooperacyjny", "Prywatny"],
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    status: "scheduled",
    type: "kontrolna",
    note: "6 tyg. po endoprotezie biodra",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-005",
    date: d(0),
    time: "10:00",
    patientFirstName: "Ewa",
    patientLastName: "Lewandowska",
    patientPesel: "88010112345",
    patientGroups: ["Nowy", "Prywatny"],
    doctorId: "zawadzki",
    doctorName: "Lek. Andrzej Zawadzki",
    status: "confirmed",
    type: "konsultacja",
    note: "Pierwsza wizyta – ból kręgosłupa L-S",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-006",
    date: d(0),
    time: "10:30",
    patientFirstName: "Marek",
    patientLastName: "Szymański",
    patientPesel: "72063012345",
    patientGroups: ["NFZ"],
    doctorId: "torba",
    doctorName: "Lek. Grzegorz Torba",
    status: "completed",
    type: "rehabilitacja",
    note: "Sesja 4/10 – staw skokowy",
    departmentId: "rehabilitacja",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-007",
    date: d(0),
    time: "11:00",
    patientFirstName: "Joanna",
    patientLastName: "Dąbrowska",
    patientPesel: "95021412345",
    patientGroups: ["Prywatny"],
    doctorId: "sammoudi",
    doctorName: "Lek. Saddam Sammoudi",
    status: "cancelled",
    type: "konsultacja",
    note: "Pacjent odwołał – przełożone",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-008",
    date: d(0),
    time: "11:30",
    patientFirstName: "Tomasz",
    patientLastName: "Wójcik",
    patientPesel: "81041112345",
    patientGroups: ["VIP", "Sport"],
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    status: "confirmed",
    type: "pilna",
    note: "Ostry ból – podejrzenie uszkodzenia ACL",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-009",
    date: d(0),
    time: "12:00",
    patientFirstName: "Agnieszka",
    patientLastName: "Kamińska",
    patientPesel: "90082512345",
    patientGroups: ["Prywatny"],
    doctorId: "wenta",
    doctorName: "Lek. Tomas Wenta",
    status: "scheduled",
    type: "zabieg",
    note: "Kwalifikacja do PRP kolano L",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-010",
    date: d(0),
    time: "13:00",
    patientFirstName: "Robert",
    patientLastName: "Kaczmarek",
    patientPesel: "70050312345",
    patientGroups: ["NFZ", "Pooperacyjny"],
    doctorId: "torba",
    doctorName: "Lek. Grzegorz Torba",
    status: "confirmed",
    type: "rehabilitacja",
    note: "Pooperacyjna RHB barku",
    departmentId: "rehabilitacja",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-011",
    date: d(1),
    time: "08:00",
    patientFirstName: "Beata",
    patientLastName: "Piotrowska",
    patientPesel: "86091712345",
    patientGroups: ["Prywatny"],
    doctorId: "frankowski",
    doctorName: "Lek. Paweł Frankowski",
    status: "scheduled",
    type: "konsultacja",
    note: "Hallux valgus – konsultacja",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-012",
    date: d(1),
    time: "09:00",
    patientFirstName: "Paweł",
    patientLastName: "Grabowski",
    patientPesel: "93012812345",
    patientGroups: ["Sport", "Nowy"],
    doctorId: "sammoudi",
    doctorName: "Lek. Saddam Sammoudi",
    status: "scheduled",
    type: "konsultacja",
    note: "Ból ścięgna Achillesa",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-013",
    date: d(1),
    time: "10:30",
    patientFirstName: "Halina",
    patientLastName: "Michalska",
    patientPesel: "55061212345",
    patientGroups: ["NFZ", "VIP"],
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    status: "confirmed",
    type: "kontrolna",
    note: "Kontrola RTG po złamaniu nadgarstka",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-014",
    date: d(2),
    time: "08:30",
    patientFirstName: "Marcin",
    patientLastName: "Adamczyk",
    patientPesel: "88073012345",
    patientGroups: ["Prywatny"],
    doctorId: "zawadzki",
    doctorName: "Lek. Andrzej Zawadzki",
    status: "scheduled",
    type: "zabieg",
    note: "Iniekcja dostawowa bark",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-015",
    date: d(2),
    time: "11:00",
    patientFirstName: "Natalia",
    patientLastName: "Sikora",
    patientPesel: "98020312345",
    patientGroups: ["Prywatny", "Sport"],
    doctorId: "wenta",
    doctorName: "Lek. Tomas Wenta",
    status: "scheduled",
    type: "konsultacja",
    note: "Kontuzja kolana – bieganie",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-016",
    date: past(1),
    time: "09:00",
    patientFirstName: "Grzegorz",
    patientLastName: "Baran",
    patientPesel: "75041912345",
    patientGroups: ["Prywatny"],
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    status: "completed",
    type: "konsultacja",
    note: "Wydano skierowanie na USG",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-017",
    date: past(1),
    time: "10:00",
    patientFirstName: "Iwona",
    patientLastName: "Czarnecka",
    patientPesel: "91050812345",
    patientGroups: ["NFZ"],
    doctorId: "torba",
    doctorName: "Lek. Grzegorz Torba",
    status: "completed",
    type: "rehabilitacja",
    note: "Sesja 8/10 – zakończono plan",
    departmentId: "rehabilitacja",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-018",
    date: past(2),
    time: "14:00",
    patientFirstName: "Dariusz",
    patientLastName: "Ostrowski",
    patientPesel: "68091512345",
    patientGroups: ["Pooperacyjny"],
    doctorId: "frankowski",
    doctorName: "Lek. Paweł Frankowski",
    status: "cancelled",
    type: "kontrolna",
    note: "Nie stawił się",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-019",
    date: past(3),
    time: "08:00",
    patientFirstName: "Katarzyna",
    patientLastName: "Lis",
    patientPesel: "87062612345",
    patientGroups: ["VIP", "Prywatny"],
    doctorId: "wenta",
    doctorName: "Lek. Tomas Wenta",
    status: "completed",
    type: "konsultacja",
    note: "Zalecenia – odciążenie, orteza",
    departmentId: "poradnia",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "v-020",
    date: d(3),
    time: "09:30",
    patientFirstName: "Łukasz",
    patientLastName: "Majewski",
    patientPesel: "94011212345",
    patientGroups: ["Nowy", "Sport"],
    doctorId: "sammoudi",
    doctorName: "Lek. Saddam Sammoudi",
    status: "scheduled",
    type: "konsultacja",
    note: "Pierwsza wizyta – uraz sportowy",
    departmentId: "ortopedia",
    createdAt: now,
    updatedAt: now,
  },
];
