import type {
  EAuditEntry,
  EPrescription,
  EPrescriptionTemplate,
  EReferral,
} from "@/lib/doctor/ehealth-types";
import { subDays } from "date-fns";

const now = new Date();
const iso = (daysAgo: number, hour = 10) => {
  const d = subDays(now, daysAgo);
  d.setHours(hour, 15, 0, 0);
  return d.toISOString();
};

function audit(
  partial: Omit<EAuditEntry, "id"> & { id?: string }
): EAuditEntry {
  return {
    id: partial.id ?? `aud-${crypto.randomUUID?.().slice(0, 8) ?? Math.random().toString(36).slice(2, 10)}`,
    at: partial.at,
    action: partial.action,
    actorUserId: partial.actorUserId,
    actorName: partial.actorName,
    actorRole: partial.actorRole,
    summary: partial.summary,
  };
}

/** Seed systemowych szablonów recept */
export const SEED_E_TEMPLATES: EPrescriptionTemplate[] = [
  {
    id: "tpl-nlpz-ipp",
    name: "NLPZ + IPP",
    description: "Ketonal Forte + Omeprazol — standard bólu ortopedycznego",
    kind: "30_days",
    items: [
      {
        drugId: "drug-001",
        drugName: "Ketonal Forte",
        inn: "Ketoprofenum",
        form: "tabletki powlekane",
        strength: "100 mg",
        dosage: "1 tabl. 1×/d z posiłkiem",
        quantity: "1 op. (20 tabl.)",
        duration: "20 dni",
        frequency: "1× dziennie rano",
        notes: "Osłona IPP przy dolegliwościach żołądkowych",
      },
      {
        drugId: "drug-029",
        drugName: "Omeprazol Sandoz",
        inn: "Omeprazolum",
        form: "kapsułki",
        strength: "20 mg",
        dosage: "1 kaps. rano na czczo",
        quantity: "1 op. (28 kaps.)",
        duration: "28 dni",
        frequency: "1× dziennie",
        notes: "",
      },
    ],
    generalNotes: "NLPZ + osłona żołądka. Unikać na pusty żołądek.",
    source: "system",
    createdAt: iso(30, 9),
    updatedAt: iso(30, 9),
  },
  {
    id: "tpl-antybiotyk",
    name: "Antybiotyk standard",
    description: "Augmentin — typowy zestaw po zabiegu / infekcja",
    kind: "30_days",
    items: [
      {
        drugId: "drug-025",
        drugName: "Augmentin",
        inn: "Amoxicillinum + Acidum clavulanicum",
        form: "tabletki",
        strength: "1 g",
        dosage: "1 tabl. 2×/d",
        quantity: "1 op. (14 tabl.)",
        duration: "7 dni",
        frequency: "co 12 h",
        notes: "Pełna kuracja, z posiłkiem",
      },
    ],
    generalNotes: "Kontrola przy wysypce / biegunka. Probiotyk opcjonalnie.",
    source: "system",
    createdAt: iso(30, 9),
    updatedAt: iso(30, 9),
  },
  {
    id: "tpl-wit-d-ca",
    name: "Witamina D + wapń",
    description: "Suplementacja w osteopenii / po menopauzie / sport",
    kind: "annual",
    items: [
      {
        drugId: "drug-016",
        drugName: "Devikap",
        inn: "Cholecalciferolum",
        form: "krople",
        strength: "20 000 j.m./ml",
        dosage: "2000 j.m. 1×/d",
        quantity: "1 but. 10 ml",
        duration: "do 12 mies. (roczna)",
        frequency: "1× dziennie",
        notes: "Kontrola 25-OH D po 3 mies.",
      },
      {
        drugId: "drug-015",
        drugName: "Calcium + Vit. D3",
        inn: "Calcium carbonicum + Cholecalciferolum",
        form: "tabletki",
        strength: "500 mg + 200 j.m.",
        dosage: "1 tabl. 1–2×/d",
        quantity: "2 op. (60 tabl.)",
        duration: "do 12 mies.",
        frequency: "1–2× dziennie",
        notes: "",
      },
    ],
    generalNotes: "Recepta roczna — realizacja częściowa w aptece.",
    source: "system",
    createdAt: iso(30, 9),
    updatedAt: iso(30, 9),
  },
];

/**
 * Seed e-recept i e-skierowań powiązanych z wizytami seed.
 */
export const SEED_E_PRESCRIPTIONS: EPrescription[] = [
  {
    id: "epx-001",
    number: "4821-7390-1564",
    accessCode: "8472",
    status: "issued",
    kind: "30_days",
    visitId: "v-001",
    patientId: "p-001",
    patientName: "Anna Kowalska",
    patientPesel: "",
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    doctorPwz: "1234567",
    items: [
      {
        id: "epi-001",
        drugId: "drug-001",
        drugName: "Ketonal Forte",
        inn: "Ketoprofenum",
        form: "tabletki powlekane",
        strength: "100 mg",
        dosage: "1 tabl. 1×/d z posiłkiem",
        quantity: "1 op. (20 tabl.)",
        duration: "20 dni",
        frequency: "1× dziennie rano",
        notes: "Przy dolegliwościach żołądkowych + IPP",
      },
      {
        id: "epi-002",
        drugId: "drug-029",
        drugName: "Omeprazol Sandoz",
        inn: "Omeprazolum",
        form: "kapsułki",
        strength: "20 mg",
        dosage: "1 kaps. rano na czczo",
        quantity: "1 op. (28 kaps.)",
        duration: "28 dni",
        frequency: "1× dziennie",
        notes: "",
      },
    ],
    generalNotes: "NLPZ + osłona żołądka. Kontrola po MRI.",
    issuedAt: iso(0, 8),
    p1Ready: true,
    auditLog: [
      audit({
        id: "aud-epx001-1",
        at: iso(0, 8),
        action: "issued",
        actorUserId: "user-doctor-kiryluk",
        actorName: "Jan Kiryluk",
        actorRole: "admin",
        summary: "Wystawiono e-receptę (2 pozycje, 30-dniowa)",
      }),
      audit({
        id: "aud-epx001-2",
        at: iso(0, 8),
        action: "template_applied",
        actorUserId: "user-doctor-kiryluk",
        actorName: "Jan Kiryluk",
        actorRole: "admin",
        summary: "Szablon: NLPZ + IPP",
      }),
    ],
    createdAt: iso(0, 8),
    updatedAt: iso(0, 8),
  },
  {
    id: "epx-002",
    number: "5910-2847-6631",
    accessCode: "3019",
    status: "issued",
    kind: "annual",
    visitId: "v-003",
    patientId: "p-003",
    patientName: "Magdalena Zielińska",
    patientPesel: "",
    doctorId: "frankowski",
    doctorName: "Lek. Paweł Frankowski",
    doctorPwz: "3456789",
    items: [
      {
        id: "epi-003",
        drugId: "drug-038",
        drugName: "Voltaren Emulgel",
        inn: "Diclofenacum diethylaminum",
        form: "żel",
        strength: "1%",
        dosage: "cienka warstwa 3×/d na bark",
        quantity: "2 op. (100 g)",
        duration: "do 3 mies. (recepta roczna — realizacja częściowa)",
        frequency: "3× dziennie",
        notes: "Miejscowo, nie stosować na uszkodzoną skórę",
      },
    ],
    generalNotes: "Recepta roczna — kontynuacja leczenia miejscowego po urazie barku.",
    issuedAt: iso(2, 9),
    p1Ready: true,
    auditLog: [
      audit({
        id: "aud-epx002-1",
        at: iso(2, 9),
        action: "issued",
        actorUserId: "user-doctor-frankowski",
        actorName: "Paweł Frankowski",
        actorRole: "doctor",
        summary: "Wystawiono e-receptę roczną (1 pozycja)",
      }),
    ],
    createdAt: iso(2, 9),
    updatedAt: iso(2, 9),
  },
  {
    id: "epx-003",
    number: "1102-8841-5570",
    accessCode: "6620",
    status: "cancelled",
    kind: "30_days",
    visitId: "v-001",
    patientId: "p-001",
    patientName: "Anna Kowalska",
    patientPesel: "",
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    doctorPwz: "1234567",
    items: [
      {
        id: "epi-004",
        drugId: "drug-002",
        drugName: "Aulin",
        inn: "Nimesulidum",
        form: "saszetki",
        strength: "100 mg",
        dosage: "1 sasz. 2×/d po posiłku",
        quantity: "1 op. (30 sasz.)",
        duration: "max 15 dni",
        frequency: "2× dziennie",
        notes: "Anulowano — zmiana na Ketonal",
      },
    ],
    generalNotes: "Anulowana — zastąpiona epx-001.",
    issuedAt: iso(1, 14),
    cancelledAt: iso(0, 8),
    cancelReason: "Zmiana leku na Ketonal Forte + IPP",
    p1Ready: false,
    auditLog: [
      audit({
        id: "aud-epx003-1",
        at: iso(1, 14),
        action: "issued",
        actorUserId: "user-doctor-kiryluk",
        actorName: "Jan Kiryluk",
        actorRole: "admin",
        summary: "Wystawiono e-receptę (Aulin)",
      }),
      audit({
        id: "aud-epx003-2",
        at: iso(0, 8),
        action: "cancelled",
        actorUserId: "user-doctor-kiryluk",
        actorName: "Jan Kiryluk",
        actorRole: "admin",
        summary: "Anulowano: Zmiana leku na Ketonal Forte + IPP",
      }),
    ],
    createdAt: iso(1, 14),
    updatedAt: iso(0, 8),
  },
];

export const SEED_E_REFERRALS: EReferral[] = [
  {
    id: "eref-001",
    number: "ES-2026-004821",
    accessCode: "5512",
    status: "issued",
    visitId: "v-001",
    patientId: "p-001",
    patientName: "Anna Kowalska",
    patientPesel: "",
    doctorId: "kiryluk",
    doctorName: "Dr n. med. Jan Kiryluk",
    doctorPwz: "1234567",
    examCategory: "Obrazowanie",
    examType: "MRI kolana",
    justification:
      "Ból kolana prawego od 3 mies., podejrzenie uszkodzenia łąkotki / gonartroza. Konieczna ocena MRI przed dalszym leczeniem.",
    urgency: "normal",
    targetFacility: "Pracownia MRI — partner zewnętrzny",
    icdCode: "M17.1",
    issuedAt: iso(0, 8),
    p1Ready: true,
    auditLog: [
      audit({
        id: "aud-eref001-1",
        at: iso(0, 8),
        action: "issued",
        actorUserId: "user-doctor-kiryluk",
        actorName: "Jan Kiryluk",
        actorRole: "admin",
        summary: "Wystawiono e-skierowanie: MRI kolana",
      }),
    ],
    createdAt: iso(0, 8),
    updatedAt: iso(0, 8),
  },
  {
    id: "eref-002",
    number: "ES-2026-003910",
    accessCode: "7741",
    status: "issued",
    visitId: "v-003",
    patientId: "p-003",
    patientName: "Magdalena Zielińska",
    patientPesel: "",
    doctorId: "frankowski",
    doctorName: "Lek. Paweł Frankowski",
    doctorPwz: "3456789",
    examCategory: "Obrazowanie",
    examType: "USG stawu barkowego",
    justification:
      "Uraz barku L (siatkówka). Ból nocny, ograniczenie uniesienia. Podejrzenie impingement / uszkodzenie stożka rotatorów.",
    urgency: "urgent",
    targetFacility: "CMKW Białystok — Szymborskiej 2/U4",
    icdCode: "M75.1",
    issuedAt: iso(2, 9),
    p1Ready: true,
    auditLog: [
      audit({
        id: "aud-eref002-1",
        at: iso(2, 9),
        action: "issued",
        actorUserId: "user-doctor-frankowski",
        actorName: "Paweł Frankowski",
        actorRole: "doctor",
        summary: "Wystawiono e-skierowanie pilne: USG barku",
      }),
    ],
    createdAt: iso(2, 9),
    updatedAt: iso(2, 9),
  },
  {
    id: "eref-003",
    number: "ES-2026-002155",
    accessCode: "1903",
    status: "cancelled",
    visitId: "v-002",
    patientId: "p-002",
    patientName: "Piotr Wiśniewski",
    patientPesel: "",
    doctorId: "wenta",
    doctorName: "Lek. Tomas Wenta",
    doctorPwz: "2345678",
    examCategory: "Rehabilitacja",
    examType: "Fizjoterapia pooperacyjna",
    justification:
      "Kontrola po artroskopii — skierowanie anulowane, rehabilitacja w innym ośrodku.",
    urgency: "normal",
    targetFacility: "Do wyboru przez pacjenta",
    icdCode: "M23.2",
    issuedAt: iso(14, 11),
    cancelledAt: iso(10, 9),
    cancelReason: "Pacjent kontynuuje rehabilitację prywatnie",
    p1Ready: false,
    auditLog: [
      audit({
        id: "aud-eref003-1",
        at: iso(14, 11),
        action: "issued",
        actorUserId: "user-doctor-wenta",
        actorName: "Tomas Wenta",
        actorRole: "doctor",
        summary: "Wystawiono e-skierowanie: fizjoterapia",
      }),
      audit({
        id: "aud-eref003-2",
        at: iso(10, 9),
        action: "cancelled",
        actorUserId: "user-doctor-wenta",
        actorName: "Tomas Wenta",
        actorRole: "doctor",
        summary: "Anulowano: rehabilitacja prywatnie",
      }),
    ],
    createdAt: iso(14, 11),
    updatedAt: iso(10, 9),
  },
];
