import type {
  AppSettings,
  FacilityData,
  Room,
  StaffMember,
  VisitTypeConfig,
} from "@/lib/doctor/admin-types";

export const SEED_FACILITY: FacilityData = {
  name: "Centrum Medyczne Kiryluk & Wenta",
  shortName: "CMKW",
  regon: "200123456",
  nip: "5421234567",
  address: "ul. Szymborskiej 2/U4",
  city: "Białystok",
  postalCode: "15-698",
  phone: "+48 85 652 20 20",
  email: "kontakt@cmkirylukwenta.pl",
  website: "https://cmkirylukwenta.pl",
  workingHours: "Pn–Pt 8:00–18:00, Sob 9:00–13:00",
  nfzCode: "000000000000",
  teryt: "2061011",
  bankAccount: "12 1240 0000 0000 0000 0000 0000",
  rodConsentText:
    "Wyrażam zgodę na przetwarzanie moich danych osobowych w celu świadczenia usług medycznych zgodnie z RODO oraz ustawą o prawach pacjenta.",
  logoUrl: "/images/logo.webp",
};

export const SEED_SETTINGS: AppSettings = {
  blockDoubleBooking: true,
  requireTeleconfirm: false,
  showPeselMaskedOnly: true,
  autoEndDayReminder: true,
  allowReceptionEditNotes: false,
  smsRemindersEnabled: true,
  onlineBookingSync: true,
  strictRoomAssignment: false,
  showPricesInCalendar: false,
  requireIcdOnComplete: false,
  auditLogEnabled: true,
  weekendSlotsEnabled: false,
};

export const SEED_STAFF: StaffMember[] = [
  {
    id: "st-kiryluk",
    firstName: "Jan",
    lastName: "Kiryluk",
    title: "Dr n. med.",
    specialty: "Ortopedia i traumatologia narządu ruchu",
    pwz: "1234567",
    role: "doctor",
    branchIds: ["bialystok"],
    active: true,
    email: "jan.kiryluk@cmkw.pl",
    phone: "+48 85 123 45 01",
    doctorId: "kiryluk",
    availabilityFactor: 0.22,
  },
  {
    id: "st-wenta",
    firstName: "Tomas",
    lastName: "Wenta",
    title: "Lek.",
    specialty: "Ortopedia i traumatologia",
    pwz: "2345678",
    role: "doctor",
    branchIds: ["bialystok", "hajnowka"],
    active: true,
    email: "tomas.wenta@cmkw.pl",
    phone: "+48 85 123 45 02",
    doctorId: "wenta",
    availabilityFactor: 0.48,
  },
  {
    id: "st-frankowski",
    firstName: "Paweł",
    lastName: "Frankowski",
    title: "Lek.",
    specialty: "Ortopedia",
    pwz: "3456789",
    role: "doctor",
    branchIds: ["bialystok"],
    active: true,
    email: "p.frankowski@cmkw.pl",
    phone: "+48 85 123 45 03",
    doctorId: "frankowski",
    availabilityFactor: 0.55,
  },
  {
    id: "st-zawadzki",
    firstName: "Andrzej",
    lastName: "Zawadzki",
    title: "Lek.",
    specialty: "Ortopedia",
    pwz: "4567890",
    role: "doctor",
    branchIds: ["bialystok", "hajnowka"],
    active: true,
    email: "a.zawadzki@cmkw.pl",
    phone: "+48 85 123 45 04",
    doctorId: "zawadzki",
    availabilityFactor: 0.58,
  },
  {
    id: "st-torba",
    firstName: "Grzegorz",
    lastName: "Torba",
    title: "Lek.",
    specialty: "Ortopedia / rehabilitacja",
    pwz: "5678901",
    role: "doctor",
    branchIds: ["bialystok"],
    active: true,
    email: "g.torba@cmkw.pl",
    phone: "+48 85 123 45 05",
    doctorId: "torba",
    availabilityFactor: 0.62,
  },
  {
    id: "st-sammoudi",
    firstName: "Saddam",
    lastName: "Sammoudi",
    title: "Lek.",
    specialty: "Ortopedia",
    pwz: "6789012",
    role: "doctor",
    branchIds: ["hajnowka", "bialystok"],
    active: true,
    email: "s.sammoudi@cmkw.pl",
    phone: "+48 85 123 45 06",
    doctorId: "sammoudi",
    availabilityFactor: 0.68,
  },
  {
    id: "st-recep1",
    firstName: "Anna",
    lastName: "Nowak",
    title: "",
    specialty: "Rejestracja",
    pwz: "",
    role: "reception",
    branchIds: ["bialystok"],
    active: true,
    email: "recepcja@cmkw.pl",
    phone: "+48 85 123 45 00",
    availabilityFactor: 1,
  },
  {
    id: "st-recep2",
    firstName: "Maria",
    lastName: "Wiśniewska",
    title: "",
    specialty: "Rejestracja",
    pwz: "",
    role: "reception",
    branchIds: ["hajnowka"],
    active: true,
    email: "recepcja.hajnowka@cmkw.pl",
    phone: "+48 85 682 11 01",
    availabilityFactor: 1,
  },
  {
    id: "st-admin",
    firstName: "Admin",
    lastName: "CMKW",
    title: "",
    specialty: "Administracja",
    pwz: "",
    role: "admin",
    branchIds: ["bialystok", "hajnowka"],
    active: true,
    email: "admin@cmkw.pl",
    phone: "+48 85 123 45 99",
    availabilityFactor: 1,
  },
];

export const SEED_ROOMS: Room[] = [
  {
    id: "room-b1",
    name: "Gabinet 1 – Ortopedia",
    branchId: "bialystok",
    floor: "parter",
    notes: "Konsultacje + drobne zabiegi",
    active: true,
  },
  {
    id: "room-b2",
    name: "Gabinet 2 – Ortopedia",
    branchId: "bialystok",
    floor: "parter",
    notes: "",
    active: true,
  },
  {
    id: "room-b3",
    name: "Gabinet 3 – Rehabilitacja",
    branchId: "bialystok",
    floor: "I piętro",
    notes: "CPM / fizjoterapia",
    active: true,
  },
  {
    id: "room-b4",
    name: "Sala zabiegowa",
    branchId: "bialystok",
    floor: "parter",
    notes: "Iniekcje, opatrunki",
    active: true,
  },
  {
    id: "room-h1",
    name: "Gabinet A – Ortopedia",
    branchId: "hajnowka",
    floor: "parter",
    notes: "",
    active: true,
  },
  {
    id: "room-h2",
    name: "Gabinet B – Konsultacje",
    branchId: "hajnowka",
    floor: "parter",
    notes: "",
    active: true,
  },
];

export const SEED_VISIT_TYPES: VisitTypeConfig[] = [
  {
    id: "vt-konsultacja",
    name: "Konsultacja",
    durationMin: 20,
    mode: "stacjonarna",
    active: true,
  },
  {
    id: "vt-kontrolna",
    name: "Wizyta kontrolna",
    durationMin: 15,
    mode: "stacjonarna",
    active: true,
  },
  {
    id: "vt-zabieg",
    name: "Zabieg / iniekcja",
    durationMin: 30,
    mode: "stacjonarna",
    active: true,
  },
  {
    id: "vt-rehab",
    name: "Rehabilitacja",
    durationMin: 45,
    mode: "stacjonarna",
    active: true,
  },
  {
    id: "vt-pilna",
    name: "Wizyta pilna",
    durationMin: 20,
    mode: "stacjonarna",
    active: true,
  },
  {
    id: "vt-tele",
    name: "Teleporada",
    durationMin: 15,
    mode: "teleporada",
    active: true,
  },
];
