import type { Icd10Code } from "./icd-types";

function c(
  code: string,
  namePl: string,
  nameLa: string,
  specialty = "Ortopedia",
  kind = "Choroba",
  relatedDrugIds: string[] = []
): Icd10Code {
  return {
    code,
    namePl,
    nameLa,
    chapter: code.charAt(0).toUpperCase(),
    kind,
    specialty,
    relatedDrugIds,
  };
}

/** ~130 kodów ICD-10 — ortopedia + popularne (mock edukacyjny). */
export const SEED_ICD10: Icd10Code[] = [
  // —— M: układ ruchu ——
  c("M00.9", "Ropne zapalenie stawu, nieokreślone", "Arthritis pyogenica, non specificata", "Ortopedia", "Choroba", ["drug-024", "drug-025"]),
  c("M02.9", "Reaktywne zapalenie stawów, nieokreślone", "Arthritis reaktiva, non specificata"),
  c("M05.9", "Seropozytywne reumatoidalne zapalenie stawów, nieokreślone", "Arthritis rheumatoides seropositiva, non specificata", "Reumatologia", "Choroba", ["drug-034", "drug-035", "drug-003"]),
  c("M06.0", "Seronegatywne reumatoidalne zapalenie stawów", "Arthritis rheumatoides seronegativa", "Reumatologia", "Choroba", ["drug-034"]),
  c("M06.9", "Reumatoidalne zapalenie stawów, nieokreślone", "Arthritis rheumatoides, non specificata", "Reumatologia"),
  c("M08.0", "Młodzieńcze reumatoidalne zapalenie stawów", "Arthritis rheumatoides juvenilis", "Reumatologia"),
  c("M10.0", "Idiopatyczna dna moczanowa", "Arthritis urica idiopathica", "Reumatologia", "Choroba", ["drug-032", "drug-033"]),
  c("M10.9", "Dna moczanowa, nieokreślona", "Arthritis urica, non specificata", "Reumatologia", "Choroba", ["drug-033"]),
  c("M13.9", "Zapalenie stawów, nieokreślone", "Arthritis, non specificata"),
  c("M15.0", "Pierwotna uogólniona choroba zwyrodnieniowa stawów", "Osteoarthrosis polyarticularis primaria"),
  c("M16.0", "Pierwotna obustronna koksartroza", "Coxarthrosis primaria bilateralis", "Ortopedia", "Choroba", ["drug-003", "drug-023", "drug-018"]),
  c("M16.1", "Inna pierwotna koksartroza", "Alia coxarthrosis primaria", "Ortopedia", "Choroba", ["drug-003", "drug-022", "drug-012"]),
  c("M16.9", "Koksartroza, nieokreślona", "Coxarthrosis, non specificata"),
  c("M17.0", "Pierwotna obustronna gonartroza", "Gonarthrosis primaria bilateralis", "Ortopedia", "Choroba", ["drug-002", "drug-017", "drug-023"]),
  c("M17.1", "Inna pierwotna gonartroza", "Alia gonarthrosis primaria", "Ortopedia", "Choroba", ["drug-001", "drug-017", "drug-018", "drug-040"]),
  c("M17.9", "Gonartroza, nieokreślona", "Gonarthrosis, non specificata"),
  c("M19.0", "Pierwotna artroza innych stawów", "Osteoarthrosis primaria aliorum articulorum"),
  c("M19.9", "Artroza, nieokreślona", "Osteoarthrosis, non specificata", "Ortopedia", "Choroba", ["drug-040"]),
  c("M20.1", "Hallux valgus (nabyty)", "Hallux valgus (acquisitus)"),
  c("M20.2", "Hallux rigidus", "Hallux rigidus"),
  c("M21.4", "Płaskostopie (pes planus) (nabyte)", "Pes planus (acquisitus)"),
  c("M22.2", "Zaburzenia rzepkowo-udowe", "Disorderum patellofemoralium"),
  c("M23.2", "Uszkodzenie łąkotki w wyniku starego urazu lub oderwania", "Laesio menisci e trauma vetere"),
  c("M23.5", "Przewlekła niestabilność kolana", "Instabilitas chronica genus"),
  c("M23.8", "Inne wewnętrzne uszkodzenia kolana", "Aliae laesiones internae genus"),
  c("M24.2", "Zaburzenie więzadła", "Disorderum ligamenti"),
  c("M24.7", "Protrusio acetabuli", "Protrusio acetabuli"),
  c("M25.5", "Ból stawu", "Dolor articuli", "Ortopedia", "Objaw", ["drug-001", "drug-005", "drug-038", "drug-041"]),
  c("M25.6", "Sztywność stawu, nie sklasyfikowana gdzie indziej", "Rigiditas articuli"),
  c("M40.0", "Kifozowanie posturalne", "Kyphosis posturalis"),
  c("M41.9", "Skolioza, nieokreślona", "Scoliosis, non specificata"),
  c("M42.1", "Osteochondroza kręgosłupa dorosłych", "Osteochondrosis spinalis adultorum"),
  c("M43.1", "Spondylolisteza", "Spondylolisthesis"),
  c("M45", "Zesztywniające zapalenie stawów kręgosłupa", "Spondylitis ankylopoetica", "Reumatologia", "Choroba", ["drug-004", "drug-022", "drug-031"]),
  c("M46.1", "Zapaleniem stawów krzyżowo-biodrowych, nie sklasyfikowane gdzie indziej", "Sacroiliitis, non alibi classificata", "Reumatologia"),
  c("M47.8", "Inne spondylozy", "Aliae spondyloses"),
  c("M47.9", "Spondyloza, nieokreślona", "Spondylosis, non specificata"),
  c("M48.0", "Stenoza kanału kręgowego", "Stenosis canalis spinalis"),
  c("M48.1", "Hiperostoza ankylozująca [Forestier]", "Hyperostosis ankylosans [Forestier]"),
  c("M50.1", "Zaburzenie krążka międzykręgowego szyjnego z radikulopatią", "Disorderum disci cervicalis cum radiculopathia", "Ortopedia", "Choroba", ["drug-036", "drug-037"]),
  c("M51.1", "Zaburzenia krążków międzykręgowych lędźwiowych i innych z radikulopatią", "Disorderum disci lumbalis cum radiculopathia", "Ortopedia", "Choroba", ["drug-009", "drug-036"]),
  c("M51.2", "Inne określone przemieszczenie krążka międzykręgowego", "Alia specificata dislocatio disci intervertebralis"),
  c("M53.1", "Zespół szyjno-ramienny", "Syndroma cervicobrachiale"),
  c("M54.1", "Radikulopatia", "Radiculopathia", "Ortopedia", "Objaw", ["drug-037"]),
  c("M54.2", "Ból karku", "Cervicalgia", "Ortopedia", "Objaw", ["drug-005", "drug-009"]),
  c("M54.3", "Rwa kulszowa", "Ischias", "Ortopedia", "Objaw", ["drug-007", "drug-009", "drug-036"]),
  c("M54.4", "Lumbago z rwa kulszową", "Lumbago cum ischiade", "Ortopedia", "Objaw", ["drug-007", "drug-009", "drug-010", "drug-036"]),
  c("M54.5", "Ból w dole pleców", "Dorsalgia lumbalis", "Ortopedia", "Objaw", ["drug-001", "drug-006", "drug-010", "drug-041"]),
  c("M54.6", "Ból w piersiowym odcinku kręgosłupa", "Dorsalgia thoracica"),
  c("M54.9", "Ból grzbietu, nieokreślony", "Dorsalgia, non specificata"),
  c("M60.9", "Zapalenie mięśni, nieokreślone", "Myositis, non specificata"),
  c("M62.4", "Przykurcz mięśnia", "Contractura musculi", "Ortopedia", "Choroba", ["drug-011"]),
  c("M62.8", "Inne określone zaburzenia mięśni", "Alia specificata disordera musculorum", "Ortopedia", "Choroba", ["drug-009"]),
  c("M65.4", "Zapalenie pochewki ścięgna mięśnia zginacza długiego kciuka [de Quervain]", "Tendovaginitis de Quervain", "Ortopedia", "Choroba", ["drug-020"]),
  c("M65.9", "Zapalenie błony maziowej i pochewki ścięgna, nieokreślone", "Synovitis et tenosynovitis, non specificata", "Ortopedia", "Choroba", ["drug-019"]),
  c("M67.4", "Ganglion", "Ganglion"),
  c("M70.2", "Zapalenie kaletki wyrostka łokciowego", "Bursitis olecrani"),
  c("M70.4", "Zapalenie kaletki przedrzepkowej", "Bursitis praepatellaris"),
  c("M70.6", "Zapalenie kaletki krętarza", "Bursitis trochanterica", "Ortopedia", "Choroba", ["drug-019"]),
  c("M72.0", "Przykurcz rozcięgna dłoniowego [Dupuytren]", "Fibromatosis palmaris [Dupuytren]"),
  c("M72.2", "Guzykowatość podeszwowa", "Fibromatosis plantaris"),
  c("M75.0", "Zapalenie torebki stawowej barku", "Capsulitis adhesiva humeri"),
  c("M75.1", "Zespół stożka rotatorów", "Syndroma cuffae rotatorum", "Ortopedia", "Choroba", ["drug-019", "drug-038"]),
  c("M75.3", "Zapalne zapalenie ścięgna naramiennego", "Tendinitis calcarea"),
  c("M75.4", "Zespół ciasnoty podbarkowej", "Syndroma impingement", "Ortopedia", "Choroba", ["drug-020"]),
  c("M75.5", "Zapalenie kaletki barku", "Bursitis humeri"),
  c("M76.6", "Zapalenie ścięgna Achillesa", "Tendinitis Achillis", "Ortopedia", "Choroba", ["drug-026", "drug-038"]),
  c("M77.0", "Przyczepowe zapalenie nadkłykcia przyśrodkowego", "Epicondylitis medialis", "Ortopedia", "Choroba", ["drug-020"]),
  c("M77.1", "Przyczepowe zapalenie nadkłykcia bocznego", "Epicondylitis lateralis", "Ortopedia", "Choroba", ["drug-019"]),
  c("M77.3", "Ostroga piętowa", "Calcar calcanei"),
  c("M79.1", "Bóle mięśni", "Myalgia", "Ortopedia", "Objaw", ["drug-001", "drug-005", "drug-038"]),
  c("M79.2", "Nerwoból i zapalenie nerwu, nieokreślone", "Neuralgia et neuritis, non specificata", "Neurologia", "Objaw", ["drug-037"]),
  c("M79.3", "Panniculitis, nieokreślone", "Panniculitis, non specificata"),
  c("M79.6", "Ból w kończynie", "Dolor in extremitate"),
  c("M79.7", "Fibromialgia", "Fibromyalgia", "Reumatologia", "Choroba", ["drug-037"]),
  c("M79.8", "Inne określone zaburzenia tkanek miękkich", "Alia specificata disordera textus mollis", "Ortopedia", "Choroba", ["drug-039"]),
  c("M80.0", "Osteoporoza pomenopauzalna ze złamaniem patologicznym", "Osteoporosis postmenopausalis cum fractura pathologica", "Ortopedia", "Choroba", ["drug-012", "drug-013", "drug-014", "drug-015"]),
  c("M80.5", "Osteoporoza idiopatyczna ze złamaniem patologicznym", "Osteoporosis idiopathica cum fractura pathologica"),
  c("M81.0", "Osteoporoza pomenopauzalna", "Osteoporosis postmenopausalis", "Ortopedia", "Choroba", ["drug-012", "drug-014", "drug-015", "drug-016"]),
  c("M81.8", "Inna osteoporoza", "Alia osteoporosis"),
  c("M84.0", "Złe zrosty złamania", "Malunio fracturae"),
  c("M84.1", "Brak zrostu złamania [pseudoartroza]", "Non unio fracturae [pseudoarthrosis]", "Ortopedia", "Choroba", ["drug-008"]),
  c("M84.3", "Złamanie z przeciążenia, nie sklasyfikowane gdzie indziej", "Fractura a fatigatione"),
  c("M84.4", "Złamanie patologiczne, nie sklasyfikowane gdzie indziej", "Fractura pathologica", "Ortopedia", "Choroba", ["drug-014"]),
  c("M86.1", "Inne ostre ropne zapalenie kości i szpiku", "Alia osteomyelitis acuta purulenta", "Ortopedia", "Choroba", ["drug-025"]),
  c("M86.6", "Inne przewlekłe zapalenie kości i szpiku", "Alia osteomyelitis chronica"),
  c("M86.9", "Zapalenie kości i szpiku, nieokreślone", "Osteomyelitis, non specificata", "Ortopedia", "Choroba", ["drug-026"]),
  c("M87.0", "Jałowa martwica kości idiopatyczna", "Necrosis aseptica ossis idiopathica"),
  c("M87.9", "Jałowa martwica kości, nieokreślona", "Necrosis aseptica ossis, non specificata"),
  c("M93.0", "Złamanie nasady kości udowej (nieurazowe)", "Epiphyseolysis capitis femoris non traumatica"),
  c("M94.0", "Zespół chrzęstno-żebrowy [Tietze]", "Syndroma costochondrale [Tietze]"),
  // —— S: urazy ——
  c("S13.4", "Skręcenie i naderwanie kręgosłupa szyjnego", "Distorsio et distensio columnae cervicalis", "Ortopedia", "Uraz"),
  c("S22.0", "Złamanie kręgu piersiowego", "Fractura vertebrae thoracicae", "Ortopedia", "Uraz"),
  c("S32.0", "Złamanie kręgu lędźwiowego", "Fractura vertebrae lumbalis", "Ortopedia", "Uraz"),
  c("S42.0", "Złamanie obojczyka", "Fractura claviculae", "Ortopedia", "Uraz"),
  c("S42.2", "Złamanie górnego końca kości ramiennej", "Fractura extremitatis superioris humeri", "Ortopedia", "Uraz"),
  c("S42.3", "Złamanie trzonu kości ramiennej", "Fractura corporis humeri", "Ortopedia", "Uraz"),
  c("S43.0", "Zwichnięcie stawu ramiennego", "Luxatio articuli humeri", "Ortopedia", "Uraz"),
  c("S43.1", "Zwichnięcie stawu barkowo-obojczykowego", "Luxatio articuli acromioclavicularis", "Ortopedia", "Uraz"),
  c("S52.5", "Złamanie dolnego końca kości promieniowej", "Fractura extremitatis inferioris radii", "Ortopedia", "Uraz"),
  c("S52.6", "Złamanie dolnego końca obu kości przedramienia", "Fractura extremitatis inferioris ulnae et radii", "Ortopedia", "Uraz"),
  c("S62.3", "Złamanie innej kości śródręcza", "Fractura aliorum ossium metacarpalium", "Ortopedia", "Uraz"),
  c("S72.0", "Złamanie szyjki kości udowej", "Fractura colli femoris", "Ortopedia", "Uraz", ["drug-027", "drug-028"]),
  c("S72.1", "Złamanie przezkrętarzowe", "Fractura pertrochanterica", "Ortopedia", "Uraz", ["drug-028"]),
  c("S72.3", "Złamanie trzonu kości udowej", "Fractura corporis femoris", "Ortopedia", "Uraz"),
  c("S82.0", "Złamanie rzepki", "Fractura patellae", "Ortopedia", "Uraz"),
  c("S82.1", "Złamanie bliższego końca kości piszczelowej", "Fractura extremitatis superioris tibiae", "Ortopedia", "Uraz"),
  c("S82.6", "Złamanie kostki bocznej", "Fractura malleoli lateralis", "Ortopedia", "Uraz"),
  c("S83.2", "Rozerwanie łąkotki, świeże", "Ruptura menisci, recens", "Ortopedia", "Uraz"),
  c("S83.4", "Skręcenie i naderwanie więzadła pobocznego kolana", "Distorsio et distensio ligamenti collateralis genus", "Ortopedia", "Uraz"),
  c("S83.5", "Skręcenie i naderwanie więzadła krzyżowego kolana", "Distorsio et distensio ligamenti cruciati genus", "Ortopedia", "Uraz", ["drug-007"]),
  c("S86.0", "Uraz ścięgna Achillesa", "Laesio tendinis Achillis", "Ortopedia", "Uraz"),
  c("S92.0", "Złamanie kości piętowej", "Fractura calcanei", "Ortopedia", "Uraz"),
  c("S93.4", "Skręcenie i naderwanie stawu skokowego", "Distorsio et distensio articuli talocruralis", "Ortopedia", "Uraz", ["drug-038", "drug-039"]),
  c("S93.5", "Skręcenie i naderwanie stawów i więzadeł stopy", "Distorsio et distensio articulorum et ligamentorum pedis", "Ortopedia", "Uraz"),
  // —— T ——
  c("T14.9", "Uraz, nieokreślony", "Trauma, non specificatum", "Ortopedia", "Uraz", ["drug-007"]),
  c("T81.4", "Zakażenie po zabiegu, nie sklasyfikowane gdzie indziej", "Infectio postproceduralis", "Ortopedia", "Powikłanie", ["drug-024"]),
  c("T84.0", "Mechaniczne powikłanie wewnętrznej protezy stawu", "Complicatio mechanica prostheseos articuli internae", "Ortopedia", "Powikłanie"),
  c("T84.5", "Zakażenie i odczyn zapalny spowodowane przez endoprotezę stawu", "Infectio et reactio inflammatoria propter prosthesin articuli", "Ortopedia", "Powikłanie", ["drug-024"]),
  c("T93.1", "Następstwa złamania kości udowej", "Sequelae fracturae femoris", "Ortopedia", "Następstwa"),
  // —— A zakaźne (wybrane) ——
  c("A46", "Róża", "Erysipelas", "Choroby zakaźne", "Choroba", ["drug-025"]),
  c("A49.0", "Zakażenie gronkowcowe, nieokreślone", "Infectio staphylococcica, non specificata", "Choroby zakaźne"),
  c("B02.2", "Półpasiec z innym zajęciem układu nerwowego", "Zoster cum alia implicatione systematis nervosi", "Neurologia"),
  // —— E ——
  c("E11.9", "Cukrzyca insulinoniezależna bez powikłań", "Diabetes mellitus non insulinodependens sine complicationibus", "Diabetologia", "Choroba"),
  c("E55.9", "Niedobór witaminy D, nieokreślony", "Defectus vitamine D, non specificatus", "Endokrynologia", "Choroba", ["drug-015", "drug-016"]),
  c("E78.0", "Czysta hipercholesterolemia", "Hypercholesterolaemia pura", "Kardiologia"),
  c("E79.0", "Hiperurykemia bez objawów zapalenia stawów i tophi", "Hyperuricaemia sine signis arthritis et tophi", "Reumatologia", "Choroba", ["drug-033"]),
  // —— G ——
  c("G35", "Stwardnienie rozsiane", "Sclerosis multiplex", "Neurologia", "Choroba", ["drug-010", "drug-011"]),
  c("G56.0", "Zespół cieśni nadgarstka", "Syndroma canalis carpi", "Ortopedia", "Choroba", ["drug-036"]),
  c("G57.1", "Meralgia paresthetica", "Meralgia paraesthetica", "Neurologia", "Choroba", ["drug-036"]),
  c("G62.9", "Polineuropatia, nieokreślona", "Polyneuropathia, non specificata", "Neurologia", "Choroba", ["drug-037"]),
  c("G80", "Mózgowe porażenie dziecięce", "Paralysis cerebralis infantilis", "Neurologia", "Choroba", ["drug-011"]),
  c("G81", "Porażenie połowicze", "Hemiplegia", "Neurologia", "Choroba", ["drug-009"]),
  // —— I ——
  c("I10", "Samoistne (pierwotne) nadciśnienie", "Hypertensio essentialis (primaria)", "Kardiologia", "Choroba", ["drug-042"]),
  c("I25.1", "Choroba niedokrwienna serca z miażdżycą tętnic wieńcowych", "Morbus ischemicus cordis atheroscleroticus", "Kardiologia", "Choroba", ["drug-042"]),
  c("I26.9", "Zator tętnicy płucnej bez wzmianki o ostrym sercu płucnym", "Embolia arteriae pulmonalis sine cor pulmonale acuto", "Kardiologia", "Choroba", ["drug-027"]),
  c("I82.9", "Zator i zakrzep żyły, nieokreślony", "Embolia et thrombosis venae, non specificata", "Kardiologia", "Choroba", ["drug-028"]),
  // —— J ——
  c("J06.9", "Ostre zakażenie górnych dróg oddechowych, nieokreślone", "Infectio acuta tractus respiratorii superioris, non specificata", "POZ", "Choroba", ["drug-025"]),
  // —— K ——
  c("K21.0", "Choroba refluksowa przełyku z zapaleniem przełyku", "Morbus refluxus oesophageus cum oesophagitis", "Gastroenterologia", "Choroba", ["drug-029"]),
  c("K21.9", "Choroba refluksowa przełyku bez zapalenia przełyku", "Morbus refluxus oesophageus sine oesophagitis", "Gastroenterologia", "Choroba", ["drug-030"]),
  c("K25.9", "Wrzód żołądka, nieokreślony jako ostry lub przewlekły, bez krwotoku lub perforacji", "Ulcus ventriculi", "Gastroenterologia", "Choroba", ["drug-029"]),
  c("K29.7", "Zapalenie żołądka, nieokreślone", "Gastritis, non specificata", "Gastroenterologia", "Choroba", ["drug-030"]),
  // —— L ——
  c("L03.1", "Ropień skóry, czyrak i czyrak gromadny kończyny", "Abscessus cutis, furunculus et carbunculus membri", "Dermatologia", "Choroba", ["drug-024"]),
  c("L08.9", "Miejscowe zakażenie skóry i tkanki podskórnej, nieokreślone", "Infectio localis cutis et subcutis, non specificata", "Dermatologia", "Choroba", ["drug-025"]),
  c("L40.5", "Łuszczyca stawowa", "Psoriasis arthropathica", "Reumatologia", "Choroba", ["drug-034"]),
  // —— R ——
  c("R52", "Ból, nie sklasyfikowany gdzie indziej", "Dolor, non alibi classificatus", "POZ", "Objaw", ["drug-005", "drug-006"]),
  c("R26.2", "Trudności w chodzeniu, nie sklasyfikowane gdzie indziej", "Difficultas ambulandi"),
  // —— Z ——
  c("Z47.0", "Kontrola po artroplastyce", "Cura post arthroplasty", "Ortopedia", "Czynnik zdrowotny"),
  c("Z96.6", "Obecność endoprotezy stawu", "Praesentia prostheseos articuli", "Ortopedia", "Czynnik zdrowotny", ["drug-027", "drug-028"]),
  c("Z96.7", "Obecność innych implantów kości i ścięgien", "Praesentia aliorum implantatorum ossis et tendinis", "Ortopedia", "Czynnik zdrowotny"),
  c("Z98.1", "Stan po artrodezie", "Status post arthrodesin", "Ortopedia", "Czynnik zdrowotny"),
];

export function getIcdByCode(code: string): Icd10Code | undefined {
  return SEED_ICD10.find((x) => x.code.toUpperCase() === code.toUpperCase());
}
