import type { Drug } from "@/lib/doctor/drug-types";

function d(
  partial: Omit<
    Drug,
    | "contraindications"
    | "warnings"
    | "interactions"
    | "pregnancyLactation"
    | "sideEffects"
    | "overdose"
    | "mechanism"
    | "composition"
  > &
    Partial<Drug>
): Drug {
  return {
    contraindications:
      partial.contraindications ??
      "Nadwrażliwość na substancję czynną lub którąkolwiek substancję pomocniczą.",
    warnings:
      partial.warnings ??
      "Stosować zgodnie z zaleceniami lekarza. Nie przekraczać zalecanej dawki.",
    interactions:
      partial.interactions ??
      "Możliwe interakcje z innymi lekami – sprawdzić pełną ChPL.",
    pregnancyLactation:
      partial.pregnancyLactation ??
      "Stosowanie w ciąży i laktacji wyłącznie po ocenie korzyści i ryzyka.",
    sideEffects:
      partial.sideEffects ??
      "Mogą wystąpić działania niepożądane – zob. ChPL.",
    overdose:
      partial.overdose ??
      "W razie przedawkowania – leczenie objawowe, kontakt z ośrodkiem toksykologicznym.",
    mechanism: partial.mechanism ?? "Zgodnie z farmakodynamiką substancji czynnej.",
    composition: partial.composition ?? `${partial.inn} – substancja czynna.`,
    ...partial,
    relatedIcd10: partial.relatedIcd10 ?? [],
  } as Drug;
}

/** ~40 leków: ortopedia + ogólne (mock edukacyjny, nie zastępuje ChPL). */
export const SEED_DRUGS: Drug[] = [
  d({
    id: "drug-001",
    name: "Ketonal Forte",
    inn: "Ketoprofenum",
    manufacturer: "Sandoz",
    form: "tabletki powlekane",
    strength: "100 mg",
    packageSize: "20 tabl.",
    pricePln: 18.5,
    category: "NLPZ",
    relatedIcd10: ["M17.1", "M54.5", "M79.1"],
    indications: "Ból o nasileniu umiarkowanym i silnym, stany zapalne stawów i tkanek miękkich.",
    dosage: "1 tabl. 1–2×/d, max 200 mg/d. Z posiłkiem, popić wodą.",
    mechanism: "Inhibitor COX, działanie przeciwzapalne, przeciwbólowe i przeciwgorączkowe.",
    composition: "Ketoprofen 100 mg + substancje pomocnicze.",
  }),
  d({
    id: "drug-002",
    name: "Aulin",
    inn: "Nimesulidum",
    manufacturer: "Helsinn / Angelini",
    form: "saszetki",
    strength: "100 mg",
    packageSize: "30 sasz.",
    pricePln: 32.0,
    category: "NLPZ",
    relatedIcd10: ["M17.0", "M25.5"],
    indications: "Ostry ból, bolesne objawy choroby zwyrodnieniowej stawów (II rzut).",
    dosage: "100 mg 2×/d, max 15 dni. Po posiłku.",
    warnings: "Ryzyko hepatotoksyczności – monitorować, unikać u osób z chorobami wątroby.",
    composition: "Nimesulid 100 mg.",
  }),
  d({
    id: "drug-003",
    name: "Diclac",
    inn: "Diclofenacum natricum",
    manufacturer: "Sandoz",
    form: "tabletki o zmodyfikowanym uwalnianiu",
    strength: "75 mg",
    packageSize: "30 tabl.",
    pricePln: 22.0,
    category: "NLPZ",
    relatedIcd10: ["M16.1", "M17.1", "M54.4"],
    indications: "RZS, ZZSK, choroba zwyrodnieniowa, ból pourazowy.",
    dosage: "75–150 mg/d w 1–2 dawkach.",
    composition: "Diklofenak sodowy 75 mg.",
  }),
  d({
    id: "drug-004",
    name: "Naproxen Hasco",
    inn: "Naproxenum",
    manufacturer: "Hasco-Lek",
    form: "tabletki",
    strength: "500 mg",
    packageSize: "20 tabl.",
    pricePln: 14.9,
    category: "NLPZ",
    relatedIcd10: ["M05.9", "M45"],
    indications: "RZS, ZZSK, ostry ból mięśniowo-szkieletowy.",
    dosage: "250–500 mg 2×/d.",
  }),
  d({
    id: "drug-005",
    name: "Ibum",
    inn: "Ibuprofenum",
    manufacturer: "Hasco-Lek",
    form: "tabletki powlekane",
    strength: "400 mg",
    packageSize: "24 tabl.",
    pricePln: 12.5,
    category: "NLPZ",
    relatedIcd10: ["M79.1", "R52"],
    indications: "Ból, gorączka, stany zapalne tkanek miękkich.",
    dosage: "200–400 mg 3–4×/d, max 1200 mg/d OTC.",
  }),
  d({
    id: "drug-006",
    name: "Paracetamol Biofarm",
    inn: "Paracetamolum",
    manufacturer: "Biofarm",
    form: "tabletki",
    strength: "500 mg",
    packageSize: "50 tabl.",
    pricePln: 8.5,
    category: "Przeciwbólowe",
    relatedIcd10: ["R52", "M54.5"],
    indications: "Ból o nasileniu lekkim do umiarkowanego, gorączka.",
    dosage: "500–1000 mg co 4–6 h, max 4 g/d u dorosłych.",
    warnings: "Nie łączyć z innymi preparatami zawierającymi paracetamol (hepatotoksyczność).",
  }),
  d({
    id: "drug-007",
    name: "Tramal",
    inn: "Tramadoli hydrochloridum",
    manufacturer: "Grünenthal",
    form: "kapsułki",
    strength: "50 mg",
    packageSize: "20 kaps.",
    pricePln: 28.0,
    category: "Opioidy",
    relatedIcd10: ["M54.4", "S83.5", "T14.9"],
    indications: "Ból o nasileniu umiarkowanym do silnego.",
    dosage: "50–100 mg co 4–6 h, max 400 mg/d.",
    interactions: "SSRI, IMAO, alkohol – ryzyko zespołu serotoninowego / depresji OUN.",
  }),
  d({
    id: "drug-008",
    name: "Oxycodone Polfarmex",
    inn: "Oxycodoni hydrochloridum",
    manufacturer: "Polfarmex",
    form: "tabletki o przedłużonym uwalnianiu",
    strength: "10 mg",
    packageSize: "28 tabl.",
    pricePln: 45.0,
    category: "Opioidy",
    relatedIcd10: ["M84.1", "C79.5"],
    indications: "Silny ból wymagający opioidów (np. pooperacyjny, nowotworowy).",
    dosage: "Indywidualnie, zwykle 10 mg 2×/d (RP).",
  }),
  d({
    id: "drug-009",
    name: "Mydocalm",
    inn: "Tolperisoni hydrochloridum",
    manufacturer: "Gedeon Richter",
    form: "tabletki powlekane",
    strength: "150 mg",
    packageSize: "30 tabl.",
    pricePln: 35.0,
    category: "Miorelaksanty",
    relatedIcd10: ["M54.4", "M62.8", "G81"],
    indications: "Spastyczność mięśni, ból kręgosłupa z napięciem mięśniowym.",
    dosage: "50–150 mg 3×/d.",
  }),
  d({
    id: "drug-010",
    name: "Sirdalud",
    inn: "Tizanidinum",
    manufacturer: "Novartis",
    form: "tabletki",
    strength: "4 mg",
    packageSize: "30 tabl.",
    pricePln: 42.0,
    category: "Miorelaksanty",
    relatedIcd10: ["M54.5", "G35"],
    indications: "Spastyczność, bolesne skurcze mięśni.",
    dosage: "2–4 mg 3×/d, stopniowo.",
    interactions: "Ciprofloksacyna, fluwoksamina – silny wzrost stężenia tizanidyny.",
  }),
  d({
    id: "drug-011",
    name: "Baclofen Polpharma",
    inn: "Baclofenum",
    manufacturer: "Polpharma",
    form: "tabletki",
    strength: "10 mg",
    packageSize: "50 tabl.",
    pricePln: 19.0,
    category: "Miorelaksanty",
    relatedIcd10: ["G80", "G35", "M62.4"],
    indications: "Spastyczność pochodzenia rdzeniowego i mózgowego.",
    dosage: "5–10 mg 3×/d, zwiększać ostrożnie.",
  }),
  d({
    id: "drug-012",
    name: "Fosamax",
    inn: "Acidum alendronicum",
    manufacturer: "MSD",
    form: "tabletki",
    strength: "70 mg",
    packageSize: "4 tabl.",
    pricePln: 48.0,
    category: "Osteoporoza",
    relatedIcd10: ["M80.0", "M81.0"],
    indications: "Osteoporoza pomenopauzalna, osteoporoza u mężczyzn, GIO.",
    dosage: "70 mg 1×/tydzień, na czczo, popić wodą, nie kłaść się 30 min.",
    composition: "Kwas alendronowy 70 mg (jako alendronian sodu).",
  }),
  d({
    id: "drug-013",
    name: "Bonviva",
    inn: "Acidum ibandronicum",
    manufacturer: "Roche",
    form: "tabletki powlekane",
    strength: "150 mg",
    packageSize: "1 tabl.",
    pricePln: 95.0,
    category: "Osteoporoza",
    relatedIcd10: ["M80.0", "M81.0"],
    indications: "Osteoporoza pomenopauzalna – zapobieganie złamaniom.",
    dosage: "150 mg 1×/miesiąc, rano na czczo.",
  }),
  d({
    id: "drug-014",
    name: "Prolia",
    inn: "Denosumabum",
    manufacturer: "Amgen",
    form: "roztwór do wstrzykiwań",
    strength: "60 mg",
    packageSize: "1 amp.-strzyk.",
    pricePln: 890.0,
    category: "Osteoporoza",
    relatedIcd10: ["M80.0", "M81.0", "M84.4"],
    indications: "Osteoporoza ze zwiększonym ryzykiem złamań.",
    dosage: "60 mg s.c. co 6 miesięcy + Ca i wit. D.",
  }),
  d({
    id: "drug-015",
    name: "Calcium + Vit. D3",
    inn: "Calcii carbonas + Colecalciferolum",
    manufacturer: "Polfa",
    form: "tabletki do ssania",
    strength: "500 mg + 400 j.m.",
    packageSize: "60 tabl.",
    pricePln: 24.0,
    category: "Suplementacja",
    relatedIcd10: ["M81.0", "E55.9"],
    indications: "Niedobór wapnia i wit. D, wspomaganie leczenia osteoporozy.",
    dosage: "1–2 tabl./d.",
  }),
  d({
    id: "drug-016",
    name: "Devikap",
    inn: "Colecalciferolum",
    manufacturer: "Polpharma",
    form: "krople doustne",
    strength: "15 000 j.m./ml",
    packageSize: "10 ml",
    pricePln: 21.0,
    category: "Suplementacja",
    relatedIcd10: ["E55.9", "M81.0"],
    indications: "Profilaktyka i leczenie niedoboru witaminy D.",
    dosage: "Zwykle 1000–4000 j.m./d (wg 25-OH-D).",
  }),
  d({
    id: "drug-017",
    name: "Hyalgan",
    inn: "Natrium hyaluronatum",
    manufacturer: "Fidia",
    form: "roztwór do wstrzykiwań dostawowych",
    strength: "20 mg/2 ml",
    packageSize: "1 amp.",
    pricePln: 280.0,
    category: "Preparaty HA",
    relatedIcd10: ["M17.1", "M17.0"],
    indications: "Choroba zwyrodnieniowa stawu kolanowego – wiskozaugmentacja.",
    dosage: "1 iniekcja dostawowa / tydzień × 3–5 (schemat wg preparatu).",
  }),
  d({
    id: "drug-018",
    name: "Synvisc",
    inn: "Hylan G-F 20",
    manufacturer: "Sanofi",
    form: "żel do wstrzykiwań dostawowych",
    strength: "16 mg/2 ml",
    packageSize: "1 amp.-strzyk.",
    pricePln: 650.0,
    category: "Preparaty HA",
    relatedIcd10: ["M17.1", "M16.1"],
    indications: "Ból w chorobie zwyrodnieniowej stawu kolanowego/biodrowego.",
    dosage: "1–3 iniekcje dostawowe wg schematu producenta.",
  }),
  d({
    id: "drug-019",
    name: "Diprophos",
    inn: "Betamethasoni dipropionas + Betamethasoni natrii phosphas",
    manufacturer: "MSD",
    form: "zawiesina do wstrzykiwań",
    strength: "7 mg/ml",
    packageSize: "1 amp. 1 ml",
    pricePln: 38.0,
    category: "Kortykosteroidy",
    relatedIcd10: ["M75.1", "M65.9", "M77.1"],
    indications: "Miejscowe stany zapalne (kaletki, pochewki, stawy) – iniekcje.",
    dosage: "Dostawowo / okołostawowo – dawka wg lokalizacji (max częstotliwość!).",
    warnings: "Ograniczyć liczbę iniekcji w ten sam staw; aseptyka.",
  }),
  d({
    id: "drug-020",
    name: "Kenalog",
    inn: "Triamcinoloni acetonidum",
    manufacturer: "Bristol-Myers Squibb",
    form: "zawiesina do wstrzykiwań",
    strength: "40 mg/ml",
    packageSize: "1 amp. 1 ml",
    pricePln: 42.0,
    category: "Kortykosteroidy",
    relatedIcd10: ["M75.4", "M77.0", "M65.4"],
    indications: "Stany zapalne stawów i tkanek miękkich, entezopatie.",
    dosage: "Dostawowo 5–40 mg w zależności od stawu.",
  }),
  d({
    id: "drug-021",
    name: "Encorton",
    inn: "Prednisonum",
    manufacturer: "Polfa Pabianice",
    form: "tabletki",
    strength: "5 mg",
    packageSize: "20 tabl.",
    pricePln: 9.5,
    category: "Kortykosteroidy",
    relatedIcd10: ["M05.9", "M32.9", "M35.3"],
    indications: "Układowe choroby tkanki łącznej, zaostrzenia zapalne.",
    dosage: "Indywidualnie; często 5–60 mg/d rano.",
  }),
  d({
    id: "drug-022",
    name: "Movalis",
    inn: "Meloxicamum",
    manufacturer: "Boehringer Ingelheim",
    form: "tabletki",
    strength: "15 mg",
    packageSize: "20 tabl.",
    pricePln: 26.0,
    category: "NLPZ",
    relatedIcd10: ["M16.1", "M17.1", "M45"],
    indications: "ChZS, ZZSK, RZS – leczenie objawowe.",
    dosage: "7,5–15 mg 1×/d.",
  }),
  d({
    id: "drug-023",
    name: "Celebrex",
    inn: "Celecoxibum",
    manufacturer: "Pfizer",
    form: "kapsułki twarde",
    strength: "200 mg",
    packageSize: "30 kaps.",
    pricePln: 55.0,
    category: "NLPZ (COX-2)",
    relatedIcd10: ["M17.0", "M16.0"],
    indications: "Choroba zwyrodnieniowa, RZS – u pacjentów z ryzykiem GI.",
    dosage: "200 mg 1–2×/d.",
    warnings: "Ryzyko sercowo-naczyniowe – najniższa skuteczna dawka, najkrócej.",
  }),
  d({
    id: "drug-024",
    name: "Clindamycin MIP",
    inn: "Clindamycinum",
    manufacturer: "MIP Pharma",
    form: "kapsułki",
    strength: "300 mg",
    packageSize: "16 kaps.",
    pricePln: 29.0,
    category: "Antybiotyki",
    relatedIcd10: ["M00.9", "T84.5", "L03.1"],
    indications: "Zakażenia kości i tkanek miękkich (m.in. gronkowce, beztlenowce).",
    dosage: "150–450 mg co 6–8 h p.o.",
  }),
  d({
    id: "drug-025",
    name: "Augmentin",
    inn: "Amoxicillinum + Acidum clavulanicum",
    manufacturer: "GSK",
    form: "tabletki powlekane",
    strength: "875 mg + 125 mg",
    packageSize: "14 tabl.",
    pricePln: 36.0,
    category: "Antybiotyki",
    relatedIcd10: ["M86.1", "L08.9", "J06.9"],
    indications: "Zakażenia tkanek miękkich, profilaktyka / leczenie wg antybiogramu.",
    dosage: "1 tabl. co 12 h z posiłkiem.",
  }),
  d({
    id: "drug-026",
    name: "Ciprofloksacyna Krka",
    inn: "Ciprofloxacinum",
    manufacturer: "Krka",
    form: "tabletki powlekane",
    strength: "500 mg",
    packageSize: "10 tabl.",
    pricePln: 18.0,
    category: "Antybiotyki",
    relatedIcd10: ["M86.9", "N39.0"],
    indications: "Zakażenia kości i stawów (wybrane), zakażenia dróg moczowych.",
    dosage: "500 mg 2×/d.",
    warnings: "Ryzyko tendinopatii / pęknięcia ścięgna Achillesa.",
  }),
  d({
    id: "drug-027",
    name: "Rivaroxaban Sandoz",
    inn: "Rivaroxabanum",
    manufacturer: "Sandoz",
    form: "tabletki powlekane",
    strength: "10 mg",
    packageSize: "30 tabl.",
    pricePln: 78.0,
    category: "Antykoagulanty",
    relatedIcd10: ["I26.9", "Z96.6", "S72.0"],
    indications: "Profilaktyka VTE po endoprotezoplastyce biodra/kolana.",
    dosage: "10 mg 1×/d (schemat pooperacyjny wg zaleceń).",
  }),
  d({
    id: "drug-028",
    name: "Clexane",
    inn: "Enoxaparinum natricum",
    manufacturer: "Sanofi",
    form: "roztwór do wstrzykiwań",
    strength: "40 mg/0,4 ml",
    packageSize: "10 amp.-strzyk.",
    pricePln: 95.0,
    category: "Antykoagulanty",
    relatedIcd10: ["I82.9", "S72.1", "Z96.6"],
    indications: "Profilaktyka i leczenie VTE, w tym pooperacyjna ortopedia.",
    dosage: "40 mg s.c. 1×/d profilaktycznie (dostosować do masy/ryzyka).",
  }),
  d({
    id: "drug-029",
    name: "Omeprazol Sandoz",
    inn: "Omeprazolum",
    manufacturer: "Sandoz",
    form: "kapsułki dojelitowe",
    strength: "20 mg",
    packageSize: "28 kaps.",
    pricePln: 15.0,
    category: "Gastroprotekcja",
    relatedIcd10: ["K21.0", "K25.9"],
    indications: "Ochrona żołądka przy długotrwałym NLPZ, refluks, wrzody.",
    dosage: "20 mg 1×/d rano.",
  }),
  d({
    id: "drug-030",
    name: "Pantoprazol Actavis",
    inn: "Pantoprazolum",
    manufacturer: "Actavis",
    form: "tabletki dojelitowe",
    strength: "40 mg",
    packageSize: "28 tabl.",
    pricePln: 17.5,
    category: "Gastroprotekcja",
    relatedIcd10: ["K21.9", "K29.7"],
    indications: "Jak IPP – gastroprotekcja przy NLPZ, GERD.",
    dosage: "40 mg 1×/d.",
  }),
  d({
    id: "drug-031",
    name: "Arcoxia",
    inn: "Etoricoxibum",
    manufacturer: "MSD",
    form: "tabletki powlekane",
    strength: "90 mg",
    packageSize: "28 tabl.",
    pricePln: 72.0,
    category: "NLPZ (COX-2)",
    relatedIcd10: ["M17.1", "M10.0", "M45"],
    indications: "ChZS, RZS, ZZSK, ostry dnawy napad.",
    dosage: "30–90 mg 1×/d (wskazanie zależne).",
  }),
  d({
    id: "drug-032",
    name: "Colchicine Opocalcium",
    inn: "Colchicinum",
    manufacturer: "Laboratoires Mayoly Spindler",
    form: "tabletki",
    strength: "1 mg",
    packageSize: "20 tabl.",
    pricePln: 31.0,
    category: "Dna moczanowa",
    relatedIcd10: ["M10.0", "M10.9"],
    indications: "Ostry napad dny, profilaktyka napadów.",
    dosage: "Napad: 1 mg, potem 0,5 mg co 1 h (max wg zaleceń) – ostrożnie!",
  }),
  d({
    id: "drug-033",
    name: "Allopurinol Teva",
    inn: "Allopurinolum",
    manufacturer: "Teva",
    form: "tabletki",
    strength: "100 mg",
    packageSize: "50 tabl.",
    pricePln: 11.0,
    category: "Dna moczanowa",
    relatedIcd10: ["M10.0", "E79.0"],
    indications: "Hiperurykemia, dna moczanowa – leczenie przewlekłe.",
    dosage: "100–300 mg/d, dostosować do kwasu moczowego.",
  }),
  d({
    id: "drug-034",
    name: "Methotrexat Ebewe",
    inn: "Methotrexatum",
    manufacturer: "Ebewe",
    form: "tabletki",
    strength: "2,5 mg",
    packageSize: "50 tabl.",
    pricePln: 28.0,
    category: "DMARD",
    relatedIcd10: ["M05.9", "M06.0", "L40.5"],
    indications: "RZS, łuszczycowe zapalenie stawów (niskie dawki tygodniowe).",
    dosage: "Zwykle 10–25 mg 1×/tydzień + kwas foliowy.",
    warnings: "Tylko 1×/tydzień! Monitorować morfologię, wątrobę, nerki.",
  }),
  d({
    id: "drug-035",
    name: "Sulfasalazin EN",
    inn: "Sulfasalazinum",
    manufacturer: "Krka",
    form: "tabletki dojelitowe",
    strength: "500 mg",
    packageSize: "50 tabl.",
    pricePln: 34.0,
    category: "DMARD",
    relatedIcd10: ["M05.9", "M45"],
    indications: "RZS, ZZSK (wybrane przypadki).",
    dosage: "Stopniowo do 2–3 g/d w dawkach podzielonych.",
  }),
  d({
    id: "drug-036",
    name: "Gabapentin Teva",
    inn: "Gabapentinum",
    manufacturer: "Teva",
    form: "kapsułki twarde",
    strength: "300 mg",
    packageSize: "50 kaps.",
    pricePln: 27.0,
    category: "Ból neuropatyczny",
    relatedIcd10: ["M54.4", "G56.0", "G57.1"],
    indications: "Ból neuropatyczny, neuralgia, radikulopatia (objawowo).",
    dosage: "Stopniowo 300–3600 mg/d w 3 dawkach.",
  }),
  d({
    id: "drug-037",
    name: "Lyrica",
    inn: "Pregabalinum",
    manufacturer: "Pfizer",
    form: "kapsułki twarde",
    strength: "75 mg",
    packageSize: "56 kaps.",
    pricePln: 68.0,
    category: "Ból neuropatyczny",
    relatedIcd10: ["M54.1", "G62.9", "M79.2"],
    indications: "Ból neuropatyczny obwodowy i ośrodkowy, fibromialgia (wskazania).",
    dosage: "75–150 mg 2×/d, max 600 mg/d.",
  }),
  d({
    id: "drug-038",
    name: "Voltaren Emulgel",
    inn: "Diclofenacum diethylaminum",
    manufacturer: "GSK",
    form: "żel",
    strength: "10 mg/g (1%)",
    packageSize: "100 g",
    pricePln: 29.0,
    category: "NLPZ miejscowe",
    relatedIcd10: ["M79.1", "M25.5", "S93.4"],
    indications: "Miejscowy ból pourazowy i reumatyczny tkanek miękkich.",
    dosage: "2–4 g żelu 3–4×/d na skórę w miejscu bólu.",
  }),
  d({
    id: "drug-039",
    name: "Traumeel S",
    inn: "Preparat złożony (homeopatyczny)",
    manufacturer: "Heel",
    form: "maść",
    strength: "—",
    packageSize: "50 g",
    pricePln: 36.0,
    category: "Miejscowe / wspomagające",
    relatedIcd10: ["S93.4", "M79.8"],
    indications: "Wspomagająco w urazach tkanek miękkich, stłuczeniach (tradycyjnie).",
    dosage: "Cienka warstwa 2–3×/d.",
    mechanism: "Preparat złożony – działanie wspomagające (brak standardowej farmakodynamiki).",
  }),
  d({
    id: "drug-040",
    name: "Chondroitin Complex",
    inn: "Chondroitini sulfas + Glucosaminum",
    manufacturer: "Biofarm",
    form: "kapsułki",
    strength: "400 mg + 500 mg",
    packageSize: "60 kaps.",
    pricePln: 52.0,
    category: "Chondroprotekcja",
    relatedIcd10: ["M17.1", "M16.1", "M19.9"],
    indications: "Wspomaganie w chorobie zwyrodnieniowej stawów (OTC/suplement).",
    dosage: "1–2 kaps. 1–2×/d z posiłkiem.",
  }),
  d({
    id: "drug-041",
    name: "Xefo Rapid",
    inn: "Lornoxicamum",
    manufacturer: "Takeda",
    form: "tabletki powlekane",
    strength: "8 mg",
    packageSize: "20 tabl.",
    pricePln: 33.0,
    category: "NLPZ",
    relatedIcd10: ["M54.5", "M25.5"],
    indications: "Ostry ból o nasileniu lekkim do umiarkowanego.",
    dosage: "8–16 mg/d w dawkach podzielonych.",
  }),
  d({
    id: "drug-042",
    name: "Amlopin",
    inn: "Amlodipinum",
    manufacturer: "Krka",
    form: "tabletki",
    strength: "5 mg",
    packageSize: "30 tabl.",
    pricePln: 14.0,
    category: "Kardiologiczne",
    relatedIcd10: ["I10", "I25.1"],
    indications: "Nadciśnienie tętnicze, choroba wieńcowa (współchorobowość ortopedyczna).",
    dosage: "5–10 mg 1×/d.",
  }),
];

export function getDrugById(id: string): Drug | undefined {
  return SEED_DRUGS.find((x) => x.id === id);
}
